import type { IntroStaffLocalizedText } from './staff-members'

export const introStaffBios = {
	CatPillager: {
		'zh-CN': `深圳人，2019 年 8 月 25 日加入氢气工艺，管委会常务委员兼服务器副服主、服务器首席建筑师、八周目欧文自治体负责人。服务器七周目、八周目的地形设计者。广东工业大学 2026 级本科生，喜欢小豆泥、欧美音乐和看音乐剧，喜欢在服务器内丢小炸弹和放歌逗你，说话活跃风趣，很喜欢用多重感叹号和问号，他也是全服开了最多 ID 的人之一。如果你和仓鼠很熟，你会觉得他很像小豆泥。仓鼠在建筑圈深耕数年，擅长欧美风格的建筑，另一位首席建筑师兼八周目卡温自治体负责人小万（xwTeng）就是仓鼠的挚友。如果你对仓鼠有兴趣，可以去看他的小红书和朋友圈。

仓鼠作为管理成员，除了协调和管理服务器内的建筑事务，也是服务器对外的一张名片。欧文自治体是他的大本营，几乎所有细节都由他亲手规划、建造。作为服务器治理方式最特殊的自治体之一，欧文境内的建设也始终遵循着一条独特的规则：任何新的开发与改动，都需要经过他的同意。仓鼠之所以有如此堪比服主和管委会的超级神权，关键在于他独特的创造力。欧美古典与现代建筑一直是仓鼠最擅长的风格。自 2019 年加入氢气工艺以来，从四周目加入旧巷到开始单干，再到五周目的西海（2020）、六周目（2022）的赫尔海姆、七周目的欧文，再到八周目重新开始的欧文群岛，都一步步见证了仓鼠的成长。

在建筑以外，他也在发挥他独特的整合和创造能力。仓鼠很喜欢原版建筑和方块，也喜欢机械动力。六周目的秘密基地、飞机起飞基地、别墅区防炸系统，都是他的杰作。他不会写 Mod，目前也可能不太擅长代码，但他是一个很好的 Player。他会用命令方块和机械动力凑出一堆能用、可维护的设施，这种对游戏的热情是难能可贵的。如果说仓鼠只会建筑，这未免太谦虚，也太侮辱人了。从西海到欧文，从 12 岁到 18 岁。城市被他重建了无数次，但在潜移默化中积累的能力不会被重置。六年的时间里，他留下的不只是建筑，还有愈发鲜明的审美、巧思、秩序与创造。`,
		'zh-TW': `深圳人，2019 年 8 月 25 日加入氫氣工藝，管理委員會常務委員兼伺服器副服主、伺服器首席建築師、八週目歐文自治體負責人。伺服器七週目、八週目的地形設計者。廣東工業大學 2026 級本科生，喜歡小豆泥、歐美音樂和看音樂劇，喜歡在伺服器內丟小炸彈和放歌逗你，說話活躍風趣，很喜歡用多重驚嘆號和問號，他也是全服開了最多 ID 的人之一。如果你和倉鼠很熟，你會覺得他很像小豆泥。倉鼠在建築圈深耕數年，擅長歐美風格的建築，另一位首席建築師兼八週目卡溫自治體負責人小萬（xwTeng）就是倉鼠的摯友。如果你對倉鼠有興趣，可以去看他的小紅書和朋友圈。

倉鼠作為管理成員，除了協調和管理伺服器內的建築事務，也是伺服器對外的一張名片。歐文自治體是他的大本營，幾乎所有細節都由他親手規劃、建造。作為伺服器治理方式最特殊的自治體之一，歐文境內的建設也始終遵循著一條獨特的規則：任何新的開發與改動，都需要經過他的同意。倉鼠之所以有如此堪比服主和管理委員會的超級神權，關鍵在於他獨特的創造力。歐美古典與現代建築一直是倉鼠最擅長的風格。自 2019 年加入氫氣工藝以來，從四週目加入舊巷到開始單幹，再到五週目的西海（2020）、六週目（2022）的赫爾海姆、七週目的歐文，再到八週目重新開始的歐文群島，都一步步見證了倉鼠的成長。

在建築以外，他也在發揮他獨特的整合和創造能力。倉鼠很喜歡原版建築和方塊，也喜歡機械動力。六週目的秘密基地、飛機起飛基地、別墅區防炸系統，都是他的傑作。他不會寫 Mod，目前也可能不太擅長程式碼，但他是一個很好的 Player。他會用命令方塊和機械動力湊出一堆能用、可維護的設施，這種對遊戲的熱情是難能可貴的。如果說倉鼠只會建築，這未免太謙虛，也太侮辱人了。從西海到歐文，從 12 歲到 18 歲。城市被他重建了無數次，但在潛移默化中積累的能力不會被重置。六年的時間裡，他留下的不只是建築，還有愈發鮮明的審美、巧思、秩序與創造。`,
		'en-US': `A Shenzhen native, CatPillager joined HydCraft on August 25, 2019. He is a Standing Member of the Management Committee and Deputy Server Owner, the server's Chief Architect, and the leader of the Owen autonomous community in Season 8. He designed the terrain for Seasons 7 and 8. An undergraduate in Guangdong University of Technology's class of 2026, he likes Chiikawa, Western music, and musicals. He enjoys dropping little bombs and playing music to tease you on the server, speaks in a lively and witty way, and loves strings of exclamation marks and question marks. He is also one of the people who have used the most IDs on the entire server. If you know CatPillager well, you will think he is a lot like Chiikawa. CatPillager has spent years immersed in the building community and excels at Western-style architecture. His close friend is xwTeng, another Chief Architect and the leader of the Calwyn autonomous community in Season 8. If CatPillager interests you, you can look at his Xiaohongshu and WeChat Moments.

As a member of management, CatPillager not only coordinates and manages building affairs on the server, but also serves as one of its public faces. The Owen autonomous community is his home base, and he personally planned and built nearly every detail. As one of the autonomous communities with the server's most distinctive form of governance, construction within Owen has always followed one unique rule: any new development or alteration requires his approval. CatPillager possesses near-divine authority comparable to that of the Server Owner and the Management Committee because of his unique creativity. Western classical and modern architecture have always been the styles he knows best. Since joining HydCraft in 2019, his growth has unfolded step by step: from joining Old Lane in Season 4 to striking out on his own, then West Sea in Season 5 (2020), Helheim in Season 6 (2022), Owen in Season 7, and the Owen Archipelago rebuilt from the ground up in Season 8.

Beyond architecture, he also applies his distinctive ability to integrate and create. CatPillager loves vanilla buildings and blocks, as well as the Create mod. The secret base, aircraft launch base, and anti-explosion system for the villa district in Season 6 are all his masterpieces. He cannot write mods and may not currently be very good at coding, but he is an excellent Player. With command blocks and Create, he assembles practical, maintainable facilities; that enthusiasm for the game is rare and valuable. To say CatPillager only knows how to build would be far too modest, and frankly insulting. From West Sea to Owen, from age 12 to 18, he rebuilt cities countless times, but the abilities accumulated almost imperceptibly along the way were never reset. Over six years, what he left behind was not only architecture, but an increasingly distinct sense of aesthetics, ingenuity, order, and creativity.`,
		'ja-JP': `深圳出身。2019 年 8 月 25 日に HydCraft へ参加し、管理委員会常務委員兼副サーバーオーナー、サーバーのチーフアーキテクト、そして第 8 シーズンのオーウェン自治体責任者を務めています。第 7・第 8 シーズンの地形デザイナーでもあります。広東工業大学の 2026 年度入学の学部生で、ちいかわ、欧米の音楽、ミュージカル鑑賞が好きです。サーバー内で小さな爆弾を落としたり、音楽を流して人をからかったりするのも好きで、話し方は活発でユーモアに富み、感嘆符や疑問符をいくつも重ねて使うのをとても好みます。また、サーバー全体でも特に多くの ID を使ってきた一人です。CatPillager と親しくなれば、彼がちいかわによく似ていると感じるでしょう。CatPillager は建築コミュニティで数年にわたり経験を積み、欧米風の建築を得意としています。もう一人のチーフアーキテクトで、第 8 シーズンのカルウィン自治体責任者でもある xwTeng は、CatPillager の親友です。CatPillager に興味があれば、彼の小紅書や WeChat モーメンツを見てみてください。

管理メンバーとしての CatPillager は、サーバー内の建築業務を調整・管理するだけでなく、サーバーが外部に見せる顔の一人でもあります。オーウェン自治体は彼の本拠地で、ほぼすべての細部を自ら計画し、建設しました。サーバー内でも特に独特な統治方式を持つ自治体の一つとして、オーウェン領内の建設には一貫して固有のルールがあります。新たな開発や変更は、すべて彼の同意を得なければなりません。CatPillager がサーバーオーナーや管理委員会にも匹敵するほどの絶大な権限を持つ鍵は、その独自の創造力にあります。欧米の古典建築と現代建築は、常に CatPillager が最も得意としてきたスタイルです。2019 年に HydCraft へ参加して以来、第 4 シーズンに旧巷へ加わってから独立し、第 5 シーズンの西海（2020）、第 6 シーズン（2022）のヘルヘイム、第 7 シーズンのオーウェン、そして第 8 シーズンに一から再出発したオーウェン諸島に至るまで、その歩みの一つ一つが CatPillager の成長を物語っています。

建築以外でも、彼は独自の統合力と創造力を発揮しています。CatPillager はバニラの建築やブロックが大好きで、Create も好んでいます。第 6 シーズンの秘密基地、航空機発進基地、別荘地の爆破防止システムは、いずれも彼の傑作です。Mod を書くことはできず、今のところコードもあまり得意ではないかもしれませんが、彼は優れた Player です。コマンドブロックと Create を組み合わせ、実用的で保守可能な設備をいくつも作り上げます。このゲームへの情熱は、得難く貴重なものです。CatPillager にできるのは建築だけだと言うなら、それは謙遜しすぎであり、本人に失礼ですらあります。西海からオーウェンへ、12 歳から 18 歳へ。都市は何度も建て直されましたが、知らず知らずのうちに積み上げた能力がリセットされることはありません。6 年の間に彼が残したものは建築だけではなく、ますます鮮明になった美意識、工夫、秩序、そして創造性でもあります。`,
	},
	xwTeng: {
		'zh-CN': `福州人，2022 年 3 月 26 日加入氢气工艺，服务器首席建筑师、八周目卡温自治体负责人。小万同时也是另一个建筑组织 WALLER 的核心成员，在建筑圈深耕数年，擅长欧美风格的建筑，且尤其擅长酒店、高档住宅、商业空间和室内设计。相比单独完成一栋建筑，小万更喜欢把建筑放进完整的城市生活中思考。酒店应该是什么定位、餐饮和商业应该如何配套、不同项目之间又应该形成怎样的品牌体系，这些问题都是小万在建筑过程中经常会思考的。卡温的许多酒店、餐饮和城市品牌，也因此带有很明显的个人风格。

小万喜欢 K-POP，聊天时看起来相当随性、友好。如果你在服务器内和他聊天，你可能会在他说的话的结尾看到一堆感叹号！在现实中，小万是一个热爱生活的人。若是你在现实中见到小万，他会拉着你到处转悠，和你讨论某个地方的趣事和八卦，你还能在他身上闻到一点微微的香水味。

此外，小万和另一位首席建筑师仓鼠（CatPillager）很有共同话题。他们俩也是很要好的挚友。小万所负责的卡温自治体和好朋友仓鼠的欧文群岛相连。欧文和卡温都是氢气工艺八周目中最靓丽的名片。很多别人可能一笔带过的内部空间，他也会继续补完整。对他来说，一栋建筑好不好看只是第一步，里面的人应该怎样生活？这才是建筑真正完整的地方。`,
		'zh-TW': `福州人，2022 年 3 月 26 日加入氫氣工藝，伺服器首席建築師、八週目卡溫自治體負責人。小萬同時也是另一個建築組織 WALLER 的核心成員，在建築圈深耕數年，擅長歐美風格的建築，且尤其擅長酒店、高檔住宅、商業空間和室內設計。相比單獨完成一棟建築，小萬更喜歡把建築放進完整的城市生活中思考。酒店應該是什麼定位、餐飲和商業應該如何配套、不同專案之間又應該形成怎樣的品牌體系，這些問題都是小萬在建築過程中經常會思考的。卡溫的許多酒店、餐飲和城市品牌，也因此帶有很明顯的個人風格。

小萬喜歡 K-POP，聊天時看起來相當隨性、友好。如果你在伺服器內和他聊天，你可能會在他說的話的結尾看到一堆驚嘆號！在現實中，小萬是一個熱愛生活的人。若是你在現實中見到小萬，他會拉著你到處轉悠，和你討論某個地方的趣事和八卦，你還能在他身上聞到一點微微的香水味。

此外，小萬和另一位首席建築師倉鼠（CatPillager）很有共同話題。他們倆也是很要好的摯友。小萬所負責的卡溫自治體和好朋友倉鼠的歐文群島相連。歐文和卡溫都是氫氣工藝八週目中最靚麗的名片。很多別人可能一筆帶過的內部空間，他也會繼續補完整。對他來說，一棟建築好不好看只是第一步，裡面的人應該怎樣生活？這才是建築真正完整的地方。`,
		'en-US': `A Fuzhou native, xwTeng joined HydCraft on March 26, 2022. He is a Chief Architect of the server and the leader of the Calwyn autonomous community in Season 8. xwTeng is also a core member of another building organization, WALLER. He has spent years immersed in the building community and excels at Western-style architecture, with particular expertise in hotels, luxury residences, commercial spaces, and interior design. Rather than completing a building in isolation, xwTeng prefers to consider architecture as part of a complete urban life. What position should a hotel occupy? How should dining and commerce support it? What kind of brand system should different projects form together? These are questions xwTeng often considers while building. As a result, many of Calwyn's hotels, restaurants, and urban brands carry a clear personal style.

xwTeng likes K-POP and comes across as quite casual and friendly in conversation. If you chat with him on the server, you may see a whole string of exclamation marks at the end of what he says! In real life, xwTeng is someone who loves life. If you meet him in person, he will take you wandering from place to place, talk with you about local stories and gossip, and you may even catch a faint scent of perfume on him.

In addition, xwTeng has a great deal in common with CatPillager, the other Chief Architect. The two are also very close friends. The Calwyn autonomous community led by xwTeng connects to the Owen Archipelago of his good friend CatPillager. Owen and Calwyn are both among the brightest calling cards of HydCraft's Season 8. He will continue completing many interior spaces that others might gloss over. For him, whether a building looks good is only the first step. How should the people inside it live? That is what makes architecture truly complete.`,
		'ja-JP': `福州出身。2022 年 3 月 26 日に HydCraft へ参加し、サーバーのチーフアーキテクトと、第 8 シーズンのカルウィン自治体責任者を務めています。xwTeng は別の建築組織 WALLER の中核メンバーでもあり、建築コミュニティで数年にわたり経験を積んできました。欧米風の建築を得意とし、特にホテル、高級住宅、商業空間、インテリアデザインに秀でています。一棟の建物を単独で完成させることよりも、xwTeng は建築を都市生活全体の中に置いて考えることを好みます。ホテルはどのような位置付けにするべきか、飲食と商業をどう組み合わせるべきか、異なるプロジェクト同士でどのようなブランド体系を形作るべきか。こうした問いは、xwTeng が建築の過程でよく考えるものです。そのため、カルウィンの数多くのホテル、飲食店、都市ブランドには、彼の個性がはっきりと表れています。

xwTeng は K-POP が好きで、会話ではかなり気さくで親しみやすく見えます。サーバー内で彼と話すと、発言の末尾に感嘆符がいくつも並んでいるかもしれません！現実の xwTeng は、暮らしを楽しむ人です。実際に会えば、彼はあなたを連れてあちこち歩き回り、その土地の面白い話や噂話を語ってくれるでしょう。そして彼から、ほのかな香水の香りを感じるかもしれません。

さらに xwTeng は、もう一人のチーフアーキテクトである CatPillager と共通の話題をたくさん持っています。二人はとても仲の良い親友でもあります。xwTeng が担当するカルウィン自治体は、親友 CatPillager のオーウェン諸島とつながっています。オーウェンとカルウィンは、どちらも HydCraft 第 8 シーズンを代表する最も華やかな顔です。他の人なら簡単に済ませてしまうような内部空間も、彼は最後まで完成させます。彼にとって、建物の見栄えが良いかどうかは最初の一歩にすぎません。その中で人はどう暮らすべきなのか。それこそが、建築を本当の意味で完成させるものです。`,
	},
	RUSH132: {
		'zh-CN': `深圳人，2026 年 7 月 29 日加入氢气工艺，八周目卡温自治体参与者，与小万、Kevin 一同建设卡温，是彼此的搭档。擅长欧美风格的建筑和城市整体架构搭建。总的来说，是一体机。`,
		'zh-TW': `深圳人，2026 年 7 月 29 日加入氫氣工藝，八週目卡溫自治體參與者，與小萬、Kevin 一同建設卡溫，是彼此的搭檔。擅長歐美風格的建築和城市整體架構搭建。總的來說，是一體機。`,
		'en-US': `A Shenzhen native, RUSH132 joined HydCraft on July 29, 2026. A participant in the Calwyn autonomous community in Season 8, he builds Calwyn alongside xwTeng and Kezzyblue, each serving as the others' partner. He excels at Western-style architecture and building the overall structure of a city. In short, he is an all-in-one machine.`,
		'ja-JP': `深圳出身。2026 年 7 月 29 日に HydCraft へ参加し、第 8 シーズンのカルウィン自治体に参加しています。xwTeng、Kezzyblue と共にカルウィンを建設し、互いのパートナーを務めています。欧米風建築と都市全体の構造づくりを得意としています。総じて言えば、オールインワンです。`,
	},
	Kezzyblue: {
		'zh-CN': `郑州人，2026 年 8 月 12 日加入氢气工艺，八周目卡温自治体参与者，与小万、RUSH 一同建设卡温，是彼此的搭档。擅长欧美风格的建筑和城市整体架构搭建。总的来说，是一体机。`,
		'zh-TW': `鄭州人，2026 年 8 月 12 日加入氫氣工藝，八週目卡溫自治體參與者，與小萬、RUSH 一同建設卡溫，是彼此的搭檔。擅長歐美風格的建築和城市整體架構搭建。總的來說，是一體機。`,
		'en-US': `A Zhengzhou native, Kezzyblue joined HydCraft on August 12, 2026. A participant in the Calwyn autonomous community in Season 8, he builds Calwyn alongside xwTeng and RUSH132, each serving as the others' partner. He excels at Western-style architecture and building the overall structure of a city. In short, he is an all-in-one machine.`,
		'ja-JP': `鄭州出身。2026 年 8 月 12 日に HydCraft へ参加し、第 8 シーズンのカルウィン自治体に参加しています。xwTeng、RUSH132 と共にカルウィンを建設し、互いのパートナーを務めています。欧米風建築と都市全体の構造づくりを得意としています。総じて言えば、オールインワンです。`,
	},
	qixuanjun233: {
		'zh-CN': `廊坊人，2020 年 8 月 20 日加入氢气工艺，管委会常务委员兼服务器副服主、服务器资深建筑师、八周目广阳自治体负责人，沈阳师范大学 2026 级（计算机科学）本科生。七炫擅长新中式和现代简约风格的建筑，但同时他也有着无与伦比的地铁设施复原能力。他会在意道路、车站、线路和城区之间的关系，而不是等城市建完以后再直接把地铁塞进去。七炫作为管理成员，除了参与广阳的建设以外，还负责服务器的运维。氢气工艺的 Minecraft 服务端就运行在七炫的 Xenonera 云服务上。

作为项目早熟型的计算机专业学生，他在高中时期就已经接触了 C#、JavaScript 等多种技术栈，PVE 运维也是他在 2025 年开始接触的。七炫喜欢玩 Turing Complete 这一类与计算机密切相关的游戏。实际上，作为本科新生的他，已经有了一些工程师的样子。在与物理机打交道的过程中，他对很多问题的理解已经不只停留在「怎么用」，而是到了「为什么会这样」和「如何解决问题」上。

在计算机以外，他也喜欢地铁、航空、人文地理和城市规划方面的内容。如果你和他一起旅行，他会开心地拉着你在地铁车厢与车站内穿梭、在城市道路中漫游，同时讨论规划和对面那栋楼的建筑风格。平时的七炫其实很开朗、乐观，他很愿意表达自己的兴趣和情绪，碰到真正重视的事情时又会非常认真。技术、建筑和地铁看起来是不同方向，但这背后其实都是他不同侧面的体现。如果你刚好在服务器里碰到他，他可能会和你讨论鸣潮或是原神的某个新剧情或新人物，又或是复盘刚才那一局瓦罗兰特（或是 CS）。他还建了一个服务器电竞社团 HLG，已经有 10 余名电竞玩家加入其中，虽然服主柠檬大概率不知道这事。`,
		'zh-TW': `廊坊人，2020 年 8 月 20 日加入氫氣工藝，管理委員會常務委員兼伺服器副服主、伺服器資深建築師、八週目廣陽自治體負責人，瀋陽師範大學 2026 級（計算機科學）本科生。七炫擅長新中式和現代簡約風格的建築，但同時他也有著無與倫比的地鐵設施復原能力。他會在意道路、車站、線路和城區之間的關係，而不是等城市建完以後再直接把地鐵塞進去。七炫作為管理成員，除了參與廣陽的建設以外，還負責伺服器的運維。氫氣工藝的 Minecraft 服務端就運行在七炫的 Xenonera 雲服務上。

作為專案早熟型的計算機專業學生，他在高中時期就已經接觸了 C#、JavaScript 等多種技術棧，PVE 運維也是他在 2025 年開始接觸的。七炫喜歡玩 Turing Complete 這一類與計算機密切相關的遊戲。實際上，作為本科新生的他，已經有了一些工程師的樣子。在與物理機打交道的過程中，他對很多問題的理解已經不只停留在「怎麼用」，而是到了「為什麼會這樣」和「如何解決問題」上。

在計算機以外，他也喜歡地鐵、航空、人文地理和城市規劃方面的內容。如果你和他一起旅行，他會開心地拉著你在地鐵車廂與車站內穿梭、在城市道路中漫遊，同時討論規劃和對面那棟樓的建築風格。平時的七炫其實很開朗、樂觀，他很願意表達自己的興趣和情緒，碰到真正重視的事情時又會非常認真。技術、建築和地鐵看起來是不同方向，但這背後其實都是他不同側面的體現。如果你剛好在伺服器裡碰到他，他可能會和你討論鳴潮或是原神的某個新劇情或新人物，又或是複盤剛才那一局瓦羅蘭特（或是 CS）。他還建了一個伺服器電競社團 HLG，已經有 10 餘名電競玩家加入其中，雖然服主檸檬大概率不知道這事。`,
		'en-US': `A Langfang native, qixuanjun233 joined HydCraft on August 20, 2020. He is a Standing Member of the Management Committee and Deputy Server Owner, a Senior Architect of the server, the leader of the Guangyang autonomous community in Season 8, and a computer science undergraduate in Shenyang Normal University's class of 2026. qixuanjun233 excels at New Chinese and modern minimalist architecture, while also possessing an unparalleled ability to recreate metro facilities. He pays attention to the relationships among roads, stations, lines, and urban districts instead of waiting until a city is finished and then simply cramming a metro into it. As a member of management, qixuanjun233 is responsible for server operations and maintenance in addition to taking part in Guangyang's construction. HydCraft's Minecraft server runs on qixuanjun233's Xenonera cloud service.

As a computer science student who matured early through projects, he had already encountered multiple technology stacks including C# and JavaScript in high school, and began working with PVE operations in 2025. qixuanjun233 likes games closely connected to computing, such as Turing Complete. In fact, although he is a first-year undergraduate, he already shows some of the qualities of an engineer. Through working with physical servers, his understanding of many problems has moved beyond "how to use it" to "why does this happen" and "how can the problem be solved."

Outside computing, he is also interested in metros, aviation, human geography, and urban planning. If you travel with him, he will happily pull you through metro carriages and stations and along city streets, all while discussing planning and the architectural style of the building across the road. In everyday life, qixuanjun233 is actually cheerful and optimistic. He readily expresses his interests and emotions, yet becomes very serious when something truly matters to him. Technology, architecture, and metros may look like different directions, but each reflects a different side of him. If you happen to meet him on the server, he may discuss a new story or character from Wuthering Waves or Genshin Impact, or review the Valorant match he just played, perhaps a CS match instead. He also founded HLG, a server esports club that has attracted more than ten esports players, although the Server Owner Aurora_Lemon probably has no idea it exists.`,
		'ja-JP': `廊坊出身。2020 年 8 月 20 日に HydCraft へ参加し、管理委員会常務委員兼副サーバーオーナー、サーバーのシニアアーキテクト、第 8 シーズンの広陽自治体責任者を務めています。瀋陽師範大学の 2026 年度入学、コンピューターサイエンス専攻の学部生です。qixuanjun233 は新中華風とモダンミニマルの建築を得意とする一方、地下鉄施設を再現する比類のない能力も備えています。都市が完成してから地下鉄をそのまま押し込むのではなく、道路、駅、路線、市街地の関係を大切にします。管理メンバーとして、qixuanjun233 は広陽の建設に参加するほか、サーバーの運用保守も担当しています。HydCraft の Minecraft サーバーは、qixuanjun233 の Xenonera クラウドサービス上で稼働しています。

プロジェクトを通して早くから成長してきたコンピューター専攻の学生として、高校時代にはすでに C# や JavaScript など複数の技術スタックに触れており、2025 年には PVE の運用にも取り組み始めました。qixuanjun233 は Turing Complete のような、コンピューターと密接に関わるゲームを好みます。実際、大学に入ったばかりでありながら、すでにエンジニアらしさを備えています。物理サーバーと向き合う中で、多くの問題への理解は「どう使うか」にとどまらず、「なぜこうなるのか」「どう問題を解決するか」という段階に達しています。

コンピューター以外にも、地下鉄、航空、人文地理、都市計画に関するものが好きです。一緒に旅行すれば、彼はうれしそうにあなたを連れて地下鉄の車内や駅を巡り、街路を歩きながら、都市計画や向かいの建物の建築様式について話すでしょう。普段の qixuanjun233 は明るく楽観的で、自分の興味や感情を進んで表現しますが、本当に大切なことに出会うと非常に真剣になります。技術、建築、地下鉄は別々の方向に見えますが、実はそのどれもが彼の異なる一面を表しています。サーバー内で偶然会えば、『鳴潮』や『原神』の新しいストーリーやキャラクターについて話したり、さっきの Valorant、あるいは CS の一戦を振り返ったりするかもしれません。また彼は、すでに 10 人以上の e スポーツプレイヤーが参加するサーバー内 e スポーツクラブ HLG も設立しました。もっとも、サーバーオーナーの Aurora_Lemon はおそらくその存在を知りません。`,
	},
	Dotkk: {
		'zh-CN': `上海人，2025 年 2 月 15 日加入氢气工艺，服务器资深建筑师、八周目广阳自治体参与者，上海交通大学博士生。Dotkk 擅长现代简约风格的建筑，也热衷于构建一套完整的城市结构。此外，他还热衷于机械动力、航空学、MTR 等创造性极强的模组。如果你来到广阳，映入眼帘的除了广阳南岸巨大的天际线，还有巨大的机械动力设施和各种车站与机场。这些都是 Dotkk 与广阳其他建设者一同创造出的结果。

Dotkk 的本职工作与 AI 部署和算力有关，长期接触各种大模型和计算基础设施的他，经常会给服务器带来一些意想不到的惊喜。他与副服主仓鼠一起科普 Axiom 的使用，又和仓鼠、七炫一起协作，帮助服务器快速进入了八周目时代。除了 AI，他过去还接触过金融量化。不同领域的经历让他习惯于先判断一件事情究竟能不能落地，再考虑应该怎样把它做出来。

虽然 Dotkk 并非纯粹意义上的建筑领域高手，但对 Agent 工作流的深刻理解和数年的工作经验促使他形成了一套极其严密的流程，这一点在广阳的建设上充分体现了出来。他很少把大量时间耗费在重复劳动上，更习惯先拆解目标、确定流程，再利用自己熟悉的工具快速推进。这种习惯最后也融入了他的游戏风格。广阳需要天际线，但建筑速度、整体规划以及能否真正落地同样重要。对 Dotkk 来说，建筑并不一定需要一个人慢慢雕琢到极致，也可以是一项需要规划、协作、工具和流程共同完成的工程。又快又稳是他的核心。`,
		'zh-TW': `上海人，2025 年 2 月 15 日加入氫氣工藝，伺服器資深建築師、八週目廣陽自治體參與者，上海交通大學博士生。Dotkk 擅長現代簡約風格的建築，也熱衷於構建一套完整的城市結構。此外，他還熱衷於機械動力、航空學、MTR 等創造性極強的模組。如果你來到廣陽，映入眼簾的除了廣陽南岸巨大的天際線，還有巨大的機械動力設施和各種車站與機場。這些都是 Dotkk 與廣陽其他建設者一同創造出的結果。

Dotkk 的本職工作與 AI 部署和算力有關，長期接觸各種大模型和計算基礎設施的他，經常會給伺服器帶來一些意想不到的驚喜。他與副服主倉鼠一起科普 Axiom 的使用，又和倉鼠、七炫一起協作，幫助伺服器快速進入了八週目時代。除了 AI，他過去還接觸過金融量化。不同領域的經歷讓他習慣於先判斷一件事情究竟能不能落地，再考慮應該怎樣把它做出來。

雖然 Dotkk 並非純粹意義上的建築領域高手，但對 Agent 工作流的深刻理解和數年的工作經驗促使他形成了一套極其嚴密的流程，這一點在廣陽的建設上充分體現了出來。他很少把大量時間耗費在重複勞動上，更習慣先拆解目標、確定流程，再利用自己熟悉的工具快速推進。這種習慣最後也融入了他的遊戲風格。廣陽需要天際線，但建築速度、整體規劃以及能否真正落地同樣重要。對 Dotkk 來說，建築並不一定需要一個人慢慢雕琢到極致，也可以是一項需要規劃、協作、工具和流程共同完成的工程。又快又穩是他的核心。`,
		'en-US': `A Shanghai native, Dotkk joined HydCraft on February 15, 2025. He is a Senior Architect of the server, a participant in the Guangyang autonomous community in Season 8, and a doctoral student at Shanghai Jiao Tong University. Dotkk excels at modern minimalist architecture and is also passionate about constructing complete urban structures. In addition, he is enthusiastic about highly creative mods such as Create, Aeronautics, and MTR. If you come to Guangyang, beyond the immense skyline on its southern bank, you will see enormous Create machinery and all kinds of stations and airports. These are all the result of Dotkk creating together with Guangyang's other builders.

Dotkk's professional work concerns AI deployment and computing power. His long-term exposure to large models and computing infrastructure often brings unexpected surprises to the server. Together with Deputy Server Owner CatPillager, he taught others how to use Axiom, and he collaborated with CatPillager and qixuanjun233 to help the server move rapidly into the era of Season 8. Beyond AI, he has also worked with quantitative finance in the past. Experience across different fields has made him accustomed to first judging whether something can actually be implemented, then considering how it should be built.

Although Dotkk is not an expert in architecture in the purest sense, his deep understanding of Agent workflows and years of professional experience have led him to develop an exceptionally rigorous process, something fully reflected in Guangyang's construction. He rarely spends large amounts of time on repetitive work. Instead, he is more accustomed to breaking down a goal, defining the process, and then using familiar tools to advance it quickly. This habit ultimately became part of his style of play. Guangyang needs a skyline, but building speed, overall planning, and whether the plan can genuinely be delivered matter just as much. For Dotkk, architecture does not necessarily have to be slowly refined to perfection by one person. It can also be an engineering effort completed through planning, collaboration, tools, and process. Fast and dependable is his core principle.`,
		'ja-JP': `上海出身。2025 年 2 月 15 日に HydCraft へ参加し、サーバーのシニアアーキテクト、第 8 シーズンの広陽自治体参加者を務めています。上海交通大学の博士課程に在籍しています。Dotkk はモダンミニマルの建築を得意とし、完全な都市構造を作り上げることにも熱意を注いでいます。さらに、Create、Aeronautics、MTR など、創造性の非常に高い Mod にも夢中です。広陽を訪れると、南岸にそびえる巨大なスカイラインだけでなく、大規模な Create の設備や、さまざまな駅と空港が目に入ります。これらはすべて、Dotkk が広陽の他の建設者たちと共に生み出した成果です。

Dotkk の本業は AI のデプロイと計算資源に関わるもので、大規模モデルやコンピューティングインフラに長く触れてきた彼は、たびたびサーバーに思いがけない驚きをもたらします。副サーバーオーナーの CatPillager と共に Axiom の使い方を広め、さらに CatPillager、qixuanjun233 と協力して、サーバーが素早く第 8 シーズンへ移行するのを支えました。AI のほか、過去には金融のクオンツ分野にも触れています。異なる領域での経験から、まず物事が本当に実現可能かを判断し、その後でどう形にするかを考える習慣が身に付いています。

Dotkk は純粋な意味で建築分野の達人というわけではありませんが、Agent ワークフローへの深い理解と数年の職務経験から、極めて厳密なプロセスを築き上げました。それは広陽の建設に十分表れています。反復作業に長い時間を費やすことはほとんどなく、まず目標を分解して手順を定め、使い慣れたツールで素早く前進させることを好みます。この習慣はやがて、彼のプレイスタイルにも溶け込みました。広陽にはスカイラインが必要ですが、建築速度、全体計画、そして本当に実現できるかどうかも同じように重要です。Dotkk にとって建築は、一人が時間をかけて極限まで磨き上げるものだけではありません。計画、協力、ツール、プロセスを組み合わせて完成させる工程にもなり得ます。速く、しかも安定していることが彼の核心です。`,
	},
	xxlm233: {
		'zh-CN': `廊坊人，2020 年 8 月 27 日加入氢气工艺，服务器资深建筑师、八周目广阳自治体参与者，2026 级本科生。他与广阳负责人七炫是发小，也是同窗好友。与广阳的另一位参与者 Dotkk 不同，宵宵狸猫更倾向于构建日式铁路和小比例的日式风格建筑，七周目的北安正是宵宵狸猫的成果之一。在建筑和游戏以外，宵宵狸猫在铁路、人文地理、电竞等方面也颇有建树。此外，宵宵狸猫也是整个服务器最了解机圈的人之一。刷什么模块、用什么调度、怎么解 BL，都是他最好奇也最爱折腾的事情。`,
		'zh-TW': `廊坊人，2020 年 8 月 27 日加入氫氣工藝，伺服器資深建築師、八週目廣陽自治體參與者，2026 級本科生。他與廣陽負責人七炫是發小，也是同窗好友。與廣陽的另一位參與者 Dotkk 不同，宵宵狸貓更傾向於構建日式鐵路和小比例的日式風格建築，七週目的北安正是宵宵狸貓的成果之一。在建築和遊戲以外，宵宵狸貓在鐵路、人文地理、電競等方面也頗有建樹。此外，宵宵狸貓也是整個伺服器最瞭解機圈的人之一。刷什麼模組、用什麼調度、怎麼解 BL，都是他最好奇也最愛折騰的事情。`,
		'en-US': `A Langfang native, xxlm233 joined HydCraft on August 27, 2020. He is a Senior Architect of the server, a participant in the Guangyang autonomous community in Season 8, and an undergraduate in the class of 2026. He and Guangyang's leader qixuanjun233 are childhood friends as well as former classmates. Unlike Dotkk, another participant in Guangyang, xxlm233 is more inclined to build Japanese-style railways and small-scale Japanese-style architecture; Bei'an in Season 7 is one of xxlm233's creations. Beyond building and gaming, xxlm233 has also accomplished a great deal in railways, human geography, and esports. In addition, xxlm233 is one of the people who know the most about smartphones on the entire server. Which module to flash, which scheduler to use, and how to unlock the bootloader are among the things he is most curious about and most loves to tinker with.`,
		'ja-JP': `廊坊出身。2020 年 8 月 27 日に HydCraft へ参加し、サーバーのシニアアーキテクト、第 8 シーズンの広陽自治体参加者を務める、2026 年度入学の学部生です。広陽の責任者 qixuanjun233 とは幼なじみで、同級生でもあります。広陽のもう一人の参加者 Dotkk とは異なり、xxlm233 は日本風の鉄道や小規模な日本風建築を作る傾向があり、第 7 シーズンの北安も xxlm233 の成果の一つです。建築とゲーム以外でも、xxlm233 は鉄道、人文地理、e スポーツなどの分野で多くの実績を持っています。さらに、xxlm233 はサーバー全体でもスマートフォン界隈に最も詳しい一人です。どのモジュールを導入するか、どのスケジューラーを使うか、どうブートローダーをアンロックするかは、彼が最も興味を持ち、最も試行錯誤を楽しむことです。`,
	},
	Aurora_Lemon: {
		'zh-CN': `福州人，2018 年 9 月 7 日加入氢气工艺，管委会主席兼服务器服主、八周目出生点直管区负责人，福建理工大学 2026 级本科生（专升本）。作为服主，柠檬主要负责服务器的运维和方向制定，而不是建筑。相反，建筑其实是他最不擅长的内容。作为 TypeScript 全栈开发者，他为服务器构建了多个网站，如 HydCraft Portal、HydCraft Console 等。在八周目初期，他与副服主仓鼠、七炫和元老院成员 Dotkk 协力，加速推进了八周目的上线。在出生点，柠檬主要负责卑微地求人送建筑凑地方。如果你在服务器看见柠檬，他大概率不是在建东西，而是在服务器里面乱逛、转圈圈和想事情。要不然，就是用机械动力手杖拿着物理化的方块乱飞。`,
		'zh-TW': `福州人，2018 年 9 月 7 日加入氫氣工藝，管理委員會主席兼伺服器服主、八週目出生點直轄區負責人，福建理工大學 2026 級本科生（專升本）。作為服主，檸檬主要負責伺服器的運維和方向制定，而不是建築。相反，建築其實是他最不擅長的內容。作為 TypeScript 全棧開發者，他為伺服器構建了多個網站，如 HydCraft Portal、HydCraft Console 等。在八週目初期，他與副服主倉鼠、七炫和元老院成員 Dotkk 協力，加速推進了八週目的上線。在出生點，檸檬主要負責卑微地求人送建築湊地方。如果你在伺服器看見檸檬，他大概率不是在建東西，而是在伺服器裡亂逛、轉圈圈和想事情。要不然，就是用機械動力手杖拿著物理化的方塊亂飛。`,
		'en-US': `A Fuzhou native, Aurora_Lemon joined HydCraft on September 7, 2018. He is Chair of the Management Committee and Server Owner, the leader of the Spawnpoint Direct Administration District in Season 8, and an undergraduate in Fujian University of Technology's class of 2026, entering through a top-up degree program. As Server Owner, Aurora_Lemon is mainly responsible for server operations and setting its direction, not construction. In fact, building is what he is least good at. As a TypeScript full-stack developer, he has built multiple websites for the server, including HydCraft Portal and HydCraft Console. At the beginning of Season 8, he worked with Deputy Server Owner CatPillager, qixuanjun233, and Council of Elders member Dotkk to accelerate the launch of Season 8. At Spawnpoint, Aurora_Lemon mainly humbly begs people to donate buildings so there is enough to fill the place. If you see Aurora_Lemon on the server, he is probably not building anything, but wandering around, spinning in circles, and thinking. Otherwise, he is flying around with materialized blocks held by a Create staff.`,
		'ja-JP': `福州出身。2018 年 9 月 7 日に HydCraft へ参加し、管理委員会主席兼サーバーオーナー、第 8 シーズンのスポーンポイント直轄区責任者を務めています。福建理工大学の 2026 年度入学の学部生で、編入による学位課程に在籍しています。サーバーオーナーとして、Aurora_Lemon は主にサーバーの運用保守と方向性の策定を担当しており、建築ではありません。むしろ、建築は彼が最も苦手とする分野です。TypeScript のフルスタック開発者として、HydCraft Portal や HydCraft Console など、サーバーのために複数のウェブサイトを構築しました。第 8 シーズンの初期には、副サーバーオーナーの CatPillager、qixuanjun233、元老院メンバーの Dotkk と協力し、第 8 シーズンの開始を早めました。スポーンポイントでは、Aurora_Lemon は主に、場所を埋めるための建築を誰かに恭しくお願いする係です。サーバーで Aurora_Lemon を見かけても、おそらく何かを建築しているのではなく、サーバー内を歩き回ったり、ぐるぐる回ったり、考え事をしたりしています。そうでなければ、Create の杖で物質化したブロックを持って飛び回っているでしょう。`,
	},
	Xiao_awa_: {
		'zh-CN': `长沙人，2018 年 9 月 20 日加入氢气工艺，服务器管委会常务委员兼元老院书记、八周目出生点直管区参与者，2024 级（法学）本科生。身为老资历玩家，肖阿瓦作为管委会常务委员，主要充当服主柠檬的助理。不过，肖阿瓦并不是疯狂建设的那种人物，他主要负责出出主意、在出现问题时作为管委会的可靠后盾。如果你在服务器里看见肖阿瓦，他大概率是在群里边开语音聊天，边和人闲逛。肖阿瓦是一个热爱生活的人，你或许能在某些电视节目的观众席上看见他那帅气的身影，亦或是在群里问租车怎么租、驾照考什么、计算机二级过了没有。若你能在现实与他相遇，他大概率会租一辆车，和你在车上聊学业、聊生活、聊工作，最后在和你吃点东西。`,
		'zh-TW': `長沙人，2018 年 9 月 20 日加入氫氣工藝，伺服器管理委員會常務委員兼元老院書記、八週目出生點直轄區參與者，2024 級（法學）本科生。身為老資歷玩家，肖阿瓦作為管理委員會常務委員，主要充當服主檸檬的助理。不過，肖阿瓦並不是瘋狂建設的那種人物，他主要負責出出主意、在出現問題時作為管理委員會的可靠後盾。如果你在伺服器裡看見肖阿瓦，他大概率是在群裡邊開語音聊天，邊和人閒逛。肖阿瓦是一個熱愛生活的人，你或許能在某些電視節目的觀眾席上看見他那帥氣的身影，亦或是在群裡問租車怎麼租、駕照考什麼、計算機二級過了沒有。若你能在現實與他相遇，他大概率會租一輛車，和你在車上聊學業、聊生活、聊工作，最後和你吃點東西。`,
		'en-US': `A Changsha native, Xiao_awa_ joined HydCraft on September 20, 2018. He is a Standing Member of the Management Committee and Secretary of the Council of Elders, a participant in the Spawnpoint Direct Administration District in Season 8, and a law undergraduate in the class of 2024. As a veteran player and Standing Member of the Management Committee, Xiao_awa_ mainly serves as Aurora_Lemon's assistant. However, Xiao_awa_ is not the kind of person who builds frantically. He mainly offers ideas and acts as a reliable backstop for the Management Committee when problems arise. If you see Xiao_awa_ on the server, he is probably chatting over voice in a group while wandering around with someone. Xiao_awa_ loves life. You might spot his handsome figure in the audience of a television show, or see him asking in the group how to rent a car, what is on the driving test, or whether someone passed the computer proficiency exam. If you meet him in real life, he will probably rent a car, talk with you about studies, life, and work in the car, and finally eat something with you.`,
		'ja-JP': `長沙出身。2018 年 9 月 20 日に HydCraft へ参加し、サーバーの管理委員会常務委員兼元老院書記、第 8 シーズンのスポーンポイント直轄区参加者を務めています。2024 年度入学の法学部生です。古参プレイヤーである Xiao_awa_ は、管理委員会の常務委員として主に Aurora_Lemon の補佐を務めています。ただし Xiao_awa_ は、ひたすら建設するタイプではありません。主にアイデアを出し、問題が起きた際には管理委員会の頼れる後ろ盾になります。サーバーで Xiao_awa_ を見かけたなら、誰かと歩き回りながらグループでボイスチャットをしている可能性が高いでしょう。Xiao_awa_ は人生を楽しむ人です。テレビ番組の観客席で彼の格好いい姿を見かけるかもしれませんし、グループでレンタカーの借り方、運転免許試験の内容、コンピューター技能試験に合格したかどうかを尋ねているかもしれません。現実で会えば、彼はきっと車を借り、車内で学業や生活、仕事について話し、最後には何かを食べに行くでしょう。`,
	},
	Nina_Naganohara: {
		'zh-CN': `南京人，2018 年 9 月 20 日加入氢气工艺，服务器资深建筑师，八周目出生点直管区参与者，辽宁大学 2020 级（法学）本科生。afe 是跟随着服务器成长的老资历玩家，除一周目、三周目和四周目外，都有他的身影。afe 擅长中式古风建筑和现代简约风格的建筑，看似完全不同的两种风格，在他手里却都很强调比例、规划和整体秩序。作为法学专业的学生，他的能力范围不只局限于法学。他同时也是铁路、航空、人文地理和城市规划爱好者。他还喜欢旅游，如果你有机会和他相见，出现在你眼前的可能是一个认真而又不死板、很可靠的人。

相比于刻板印象中的文科生，afe 反而走出了一条广度和深度共同发展的路。他喜欢有规矩、有效率、能够真正推进事情的工作方式。相比不断讨论各种可能性，他更倾向于先把规则和规划确定下来，再把事情一件件做完。这种性格使他能够做出一些看起来很不可思议的事。你可能会见到他在群里和群友讨论网站开发、AI 编程、CI/CD。这些事情构成了一个更加立体的 afe，成熟、稳重、可交付，反而成了他的内涵。所以，他反而和计算机专业的玩家更能聊得来（没有说法学等非理工科专业聊不来的意思）。甚至，你能在服务器的 Steam 群组内看见他和别的玩家一起玩猛兽派对，或是在群里和别人讨论原神和明日方舟的新剧情。`,
		'zh-TW': `南京人，2018 年 9 月 20 日加入氫氣工藝，伺服器資深建築師，八週目出生點直轄區參與者，遼寧大學 2020 級（法學）本科生。afe 是跟隨著伺服器成長的老資歷玩家，除一週目、三週目和四週目外，都有他的身影。afe 擅長中式古風建築和現代簡約風格的建築，看似完全不同的兩種風格，在他手裡卻都很強調比例、規劃和整體秩序。作為法學專業的學生，他的能力範圍不只局限於法學。他同時也是鐵路、航空、人文地理和城市規劃愛好者。他還喜歡旅遊，如果你有機會和他相見，出現在你眼前的可能是一個認真而又不死板、很可靠的人。

相比於刻板印象中的文科生，afe 反而走出了一條廣度和深度共同發展的路。他喜歡有規矩、有效率、能夠真正推進事情的工作方式。相比不斷討論各種可能性，他更傾向於先把規則和規劃確定下來，再把事情一件件做完。這種性格使他能夠做出一些看起來很不可思議的事。你可能會見到他在群裡和群友討論網站開發、AI 編程、CI/CD。這些事情構成了一個更加立體的 afe，成熟、穩重、可交付，反而成了他的內涵。所以，他反而和計算機專業的玩家更能聊得來（沒有說法學等非理工科專業聊不來的意思）。甚至，你能在伺服器的 Steam 群組內看見他和別的玩家一起玩猛獸派對，或是在群裡和別人討論原神和明日方舟的新劇情。`,
		'en-US': `A Nanjing native, Nina_Naganohara joined HydCraft on September 20, 2018. He is a Senior Architect of the server, a participant in the Spawnpoint Direct Administration District in Season 8, and a law undergraduate at Liaoning University in the class of 2020. Nina_Naganohara is a veteran player who has grown alongside the server; he has appeared in every season except Seasons 1, 3, and 4. Nina_Naganohara excels at traditional Chinese classical architecture and modern minimalist architecture. Although these styles seem completely different, in his hands both emphasize proportion, planning, and overall order. As a law student, his abilities are not limited to law. He is also an enthusiast of railways, aviation, human geography, and urban planning. He likes travelling too. If you have the chance to meet him, you may find a serious but not rigid and very reliable person in front of you.

Compared with the stereotypical liberal arts student, Nina_Naganohara has instead followed a path that develops breadth and depth together. He likes orderly, efficient ways of working that can genuinely move things forward. Rather than endlessly discussing every possibility, he prefers to establish the rules and plan first, then finish tasks one by one. This personality allows him to do things that may look unbelievable. You may see him discussing website development, AI programming, and CI/CD with other group members. These things form a more three-dimensional Nina_Naganohara: mature, steady, and deliverable, which has become his true substance. That is why he actually finds it easier to talk with computer science players (this does not mean that he cannot talk with students of law or other non-STEM subjects). You may even see him playing Party Animals with other players in the server's Steam group, or discussing new stories from Genshin Impact and Arknights in the group.`,
		'ja-JP': `南京出身。2018 年 9 月 20 日に HydCraft へ参加し、サーバーのシニアアーキテクト、第 8 シーズンのスポーンポイント直轄区参加者を務めています。遼寧大学の 2020 年度入学、法学専攻の学部生です。Nina_Naganohara はサーバーの成長と共に歩んできた古参プレイヤーで、第 1・第 3・第 4 シーズンを除くすべてのシーズンに姿を見せています。中国古典風建築とモダンミニマル建築を得意とし、一見まったく異なる二つのスタイルを、どちらも比例、計画、全体の秩序を重視して仕上げます。法学を専攻する学生ですが、能力の範囲は法学だけに限りません。鉄道、航空、人文地理、都市計画の愛好家でもあります。旅行も好きで、会う機会があれば、真面目でありながら堅苦しくなく、とても頼りになる人に出会えるでしょう。

典型的な文系学生のイメージとは異なり、Nina_Naganohara は広さと深さを共に伸ばす道を歩んでいます。規則があり、効率的で、本当に物事を前へ進められる仕事の進め方を好みます。さまざまな可能性を延々と議論するより、まず規則と計画を決め、それから一つずつ終わらせることを選びます。この性格によって、一見すると信じられないようなことも成し遂げられます。グループで仲間とウェブサイト開発、AI プログラミング、CI/CD について話している姿を見かけるかもしれません。そうしたことが、より立体的な Nina_Naganohara を形作っています。成熟していて、落ち着いていて、成果を届けられることが、彼の中身になっています。そのため、彼はコンピューター専攻のプレイヤーのほうが話しやすいのです（法学など非理系の専攻と話せないという意味ではありません）。サーバーの Steam グループで他のプレイヤーと Party Animals を遊んでいる姿や、グループで『原神』と『アークナイツ』の新しいストーリーについて話している姿を見ることもできるでしょう。`,
	},
	FisheyeArtist59: {
		'zh-CN': `沈阳人，2021 年 4 月 18 日加入氢气工艺，服务器管委会顾问委员、服务器首席建筑师、八周目西港片区负责人，中国医科大学 2026 级博士生。题散没有非常固定的建筑风格，从七周目的莒南到八周目的西港，他的建筑更多体现出一种可靠、稳定而又精致的特点。相比追求夸张的造型和复杂的装饰，他更愿意把丰富的细节放进合理的结构里，让一栋建筑看起来完整、耐看，又不会显得花里胡哨。

在建筑之外，题散的交付能力和 UI 能力同样很强。即便并非计算机专业出身，他依旧能依靠自己的审美和对工具的理解，借助 AI 实现一套属于自己铁路公司的运行图网站。自从氢气工艺步入机械动力时代以来，题散一直都是机械动力设施建设的主力军，也是最早开始尝试这套体系的人之一。很多后来逐渐变成常规的机械动力玩法，最开始往往都是他先去研究、试错，再一点点搭出来。作为医学博士生，他的大部分时间都被实验占据，而在实验之外，Minecraft 也就成了他难得的休息时间。

当然，题散也不只是氢气工艺的成员。他同时还是临东市服务器（基岩版）的管理成员之一，在基岩版和 Java 版之间反复横跳的他，也自然能够看到两个生态各自不同的优点，并把这些经验带回自己的建筑和玩法里。现实中的题散沉稳、内敛，不太喜欢把自己放在很显眼的位置。如果你在群里看见他，他大概率是在分享自己刚刚做完的游戏截图，亦或是和人讨论游戏里的建筑、机械动力或其他技术问题。`,
		'zh-TW': `瀋陽人，2021 年 4 月 18 日加入氫氣工藝，伺服器管理委員會顧問委員、伺服器首席建築師、八週目西港片區負責人，中國醫科大學 2026 級博士生。題散沒有非常固定的建築風格，從七週目的莒南到八週目的西港，他的建築更多體現出一種可靠、穩定而又精緻的特點。相比追求誇張的造型和複雜的裝飾，他更願意把豐富的細節放進合理的結構裡，讓一棟建築看起來完整、耐看，又不會顯得花裡胡哨。

在建築之外，題散的交付能力和 UI 能力同樣很強。即便並非計算機專業出身，他依舊能依靠自己的審美和對工具的理解，借助 AI 實現一套屬於自己鐵路公司的運行圖網站。自從氫氣工藝步入機械動力時代以來，題散一直都是機械動力設施建設的主力軍，也是最早開始嘗試這套體系的人之一。很多後來逐漸變成常規的機械動力玩法，最開始往往都是他先去研究、試錯，再一點點搭出來。作為醫學博士生，他的大部分時間都被實驗佔據，而在實驗之外，Minecraft 也就成了他難得的休息時間。

當然，題散也不只是氫氣工藝的成員。他同時還是臨東市伺服器（基岩版）的管理成員之一，在基岩版和 Java 版之間反覆橫跳的他，也自然能夠看到兩個生態各自不同的優點，並把這些經驗帶回自己的建築和玩法裡。現實中的題散沉穩、內斂，不太喜歡把自己放在很顯眼的位置。如果你在群裡看見他，他大概率是在分享自己剛剛做完的遊戲截圖，亦或是和人討論遊戲裡的建築、機械動力或其他技術問題。`,
		'en-US': `A Shenyang native, FisheyeArtist59 joined HydCraft on April 18, 2021. He is an Advisory Member of the Management Committee, a Chief Architect of the server, the leader of the Xigang district in Season 8, and a doctoral student at China Medical University in the class of 2026. FisheyeArtist59 has no particularly fixed architectural style. From Junan in Season 7 to Xigang in Season 8, his buildings have more often expressed a reliable, stable, and refined character. Rather than pursuing exaggerated forms and complicated decoration, he prefers to place rich detail inside reasonable structures, making a building look complete and enduring without becoming gaudy.

Beyond architecture, FisheyeArtist59 is equally strong at delivery and UI work. Although he did not come from a computer science background, he can still rely on his aesthetic sense and understanding of tools to use AI to create a timetable website for his own railway company. Since HydCraft entered the Create era, FisheyeArtist59 has consistently been one of the main forces behind Create infrastructure and one of the earliest people to experiment with the system. Many Create practices that later became routine began with him researching and testing them, then assembling them step by step. As a medical doctoral student, most of his time is occupied by experiments; outside the lab, Minecraft has become one of his rare ways to rest.

Of course, FisheyeArtist59 is not only a member of HydCraft. He is also one of the administrators of the Lindong City server (Bedrock Edition). Moving back and forth between Bedrock and Java Edition, he naturally sees the different strengths of each ecosystem and brings that experience back to his own building and gameplay. In real life, FisheyeArtist59 is calm and reserved and does not like putting himself in the spotlight. If you see him in the group, he is probably sharing a game screenshot he just finished, or discussing in-game architecture, Create, or another technical topic with someone.`,
		'ja-JP': `瀋陽出身。2021 年 4 月 18 日に HydCraft へ参加し、サーバーの管理委員会顧問委員、チーフアーキテクト、第 8 シーズンの西港地区責任者を務めています。中国医科大学の 2026 年度入学の博士課程学生です。FisheyeArtist59 には特に固定された建築様式がありません。第 7 シーズンの莒南から第 8 シーズンの西港まで、彼の建築はむしろ信頼性、安定感、そして繊細さを表現してきました。誇張された形や複雑な装飾を追い求めるより、合理的な構造の中に豊かなディテールを収め、完全で見飽きず、それでいてけばけばしくない建物にすることを好みます。

建築以外でも、FisheyeArtist59 は納品力と UI の能力が非常に高いです。コンピューター専攻の出身ではありませんが、美的感覚とツールへの理解を頼りに、AI を使って自分の鉄道会社のダイヤグラムサイトを実現しました。HydCraft が Create の時代に入って以来、FisheyeArtist59 は Create 設備建設の主力の一人であり、この体系を最も早く試し始めた人の一人でもあります。後に当たり前になった Create の遊び方の多くは、もともと彼が先に研究と試行錯誤を重ね、少しずつ組み立てたものでした。医学博士課程の学生である彼の時間の大半は実験に占められていますが、実験の外では Minecraft が貴重な休息になっています。

もちろん、FisheyeArtist59 は HydCraft のメンバーであるだけではありません。臨東市サーバー（Bedrock 版）の管理メンバーの一人でもあります。Bedrock 版と Java 版を行き来する彼は、二つのエコシステムそれぞれの異なる長所を自然に理解し、その経験を自分の建築やプレイスタイルへ持ち帰っています。現実の FisheyeArtist59 は落ち着いて控えめで、自分を目立つ場所に置くことを好みません。グループで彼を見かけたなら、たった今完成させたゲームのスクリーンショットを共有しているか、ゲーム内の建築、Create、その他の技術的な話題について誰かと話している可能性が高いでしょう。`,
	},
} satisfies Record<string, IntroStaffLocalizedText>
